# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daniel Junho
tagline:          ''
description:      'Um novo projeto dentro de tantas ideias.'

#description:      'Um novo projeto dentro de tantas ideias <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'

url:              http://djunho.github.io/
baseurl:          /

author:
  name:           'Daniel Junho'
#  url:            https://twitter.com/djunho

paginate:         5

comments: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/djunho/djunho.github.io

social-icons:
- title: GitHub
  url: https://github.com/djunho
  class: github
- title: LinkedIn
  url: https://br.linkedin.com/pub/daniel-junho/24/7b7/249
  class: linkedin
- title: Twitter
  url: https://twitter.com/djunho
  class: twitter
- title: Facebook
  url: https://www.facebook.com/djunho
  class: facebook
- title: Feed
  url: http://danieljunho.com/atom.xml
  class: rss-feed

gems:
  - jekyll-feed

