# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Junho
tagline:          ''
description:      'Um novo projeto dentro de tantas ideias.'

url:              http://danieljunho.com
baseurl:          /

author:
  name:           'Daniel Junho'
 email:           djunho@gmail.com
   url:           http://danieljunho.com

paginate:         5

comments: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/djunho/djunho.github.io

social-icons:
- title: GitHub
  url: https://github.com/djunho
  class: github
- title: LinkedIn
  url: https://br.linkedin.com/pub/daniel-junho/24/7b7/249
  class: linkedin
- title: Twitter
  url: https://twitter.com/djunho
  class: twitter
- title: Facebook
  url: https://www.facebook.com/djunho
  class: facebook
- title: Feed
  url: http://danieljunho.com/atom.xml
  class: rss-feed

gems:
  - jekyll-feed
  - jekyll-paginate

