# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Daniel Junho
tagline:          ''
description:      'Um novo projeto dentro de tantas ideias.'
url:              http://danieljunho.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Daniel Junho'
  url:            http://danieljunho.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/djunho/djunho.github.io

disqus:
  shortname: djunho

linkedin_username: djunho

google_analytics: UA-62461815-1

social-icons:
- title: GitHub
  url: https://github.com/djunho
  class: github
- title: LinkedIn
  url: https://br.linkedin.com/pub/daniel-junho/24/7b7/249
  class: linkedin